streaming_data_types/histogram_hs00.py
streaming_data_types/nicos_cache_ns10.py
streaming_data_types/run_stop_6s4t.py

Seems like a good scheme to me

Copied the naming conventions from Matthew's code

---

README.md
streaming_data_types/logdata_f142.py
tests/test_f142.py

Closes DM-1890
Added array and alarm serialisation to f142
Added f142 to table in readme, buffer is verifiable \o/

Add array and alarm serialisation to f142

---

MANIFEST.in
README.md
README_DEV.md
requirements-dev.txt
setup.py

Splitting the readme, so there is a separate dev one and some tidying up so we can upload this to Pypi in the future (makes things easier for NICOS)

Preparation for putting on pypi

---

README.md

Clarify what verification means

---

requirements-dev.txt
setup.py

Version change for release.
Also added `wheel` to dev requirements.

Bump version to 0.6.0

---

README_DEV.md
setup.py
streaming_data_types/__init__.py
tox.ini

Created dicts so clients can query which schema are supported and retrieve the appropriate serialiser or deserialiser function.

Added way for clients to know which schema are supported.

---

streaming_data_types/logdata_f142.py
streaming_data_types/run_start_pl72.py
streaming_data_types/run_stop_6s4t.py
streaming_data_types/timestamps_tdct.py

Small quality of life improvement when using the library.

Move NameTuples to module scope so that autocomplete works

---

streaming_data_types/eventdata_ev42.py
streaming_data_types/logdata_f142.py

A couple were still returning bytearray, so I have fixed those.

All serialisation functions should return bytes

---

README_DEV.md
streaming_data_types/__init__.py
tests/test_6s4t.py
tests/test_ep00.py
tests/test_ev42.py
tests/test_f142.py
tests/test_hs00.py
tests/test_ns10.py
tests/test_pl72.py
tests/test_tdct.py
tests/test_x52f.py

Also, added tests to check they are present

Add ep00 and tdct to serialisers list

---

tests/test_f142.py
tests/test_rf5k.py
tests/test_x52f.py

Probably copy 'n' paste errors.

Noticed some stray Py2 style  and some uncommon naming

---

streaming_data_types/histogram_hs00.py

Tidies things up significantly.
Can wait for next release.

ECDC-2191: Use CreateNumpyVector where appropriate in hs00

---

streaming_data_types/action_response_answ.py

datetime throws an exception if year is ≈10000 years. This works around that. I think it is doubtful that this code will be in use in a 1000 years.

Work around for datetime limitations

---

streaming_data_types/exceptions.py
streaming_data_types/utils.py
tests/test_6s4t.py
tests/test_NDAr.py
tests/test_answ.py
tests/test_ep00.py
tests/test_ev42.py
tests/test_f142.py
tests/test_hs00.py
tests/test_ns10.py
tests/test_pl72.py
tests/test_rf5k.py
tests/test_tdct.py
tests/test_utils.py
tests/test_wrdn.py
tests/test_x52f.py

Use custom exception classes to make it clearer where the exceptions are coming from.

Use custom exceptions

---

streaming_data_types/eventdata_ev42.py

Contributes to ECDC-2191
Performance change:
| Number of events | Old implementation (seconds) | New implementation (seconds) |
|------------------|------------------------------|------------------------------|
| 10000            | 0.087                        | 0.00022                      |
| 100000           | 0.82                         | 0.0016                       |
| 1000000          | 8.10                         | 0.013                        |

Use CreateNumpyVector in ev42 serialisation

---

streaming_data_types/utils.py

Occasionally, it can be useful for clients of the module to have access to this.

Make get_schema public

---

README_DEV.md
setup.py
streaming_data_types/__init__.py

Added version number for library

---

streaming_data_types/__init__.py
streaming_data_types/action_response_answ.py
streaming_data_types/area_detector_ADAr.py
streaming_data_types/sample_environment_senv.py
streaming_data_types/timestamps_tdct.py
tests/test_ADAr.py
tests/test_answ.py
tests/test_senv.py

Add tz to datetimes

---

streaming_data_types/_version.py
streaming_data_types/run_start_pl72.py

Make recent changes to pl72 backwards compatible

---

streaming_data_types/fbschemas/run_start_pl72/RunStart.py
streaming_data_types/run_start_pl72.py
tests/test_pl72.py

Add python support for the new control topic field.

Added control_topic to pl72 run start

---

.gitignore
Jenkinsfile
README_DEV.md
tox.ini

Locally I found tox stopped working as it couldn't find the requirements files from the version specific installs.
This works for me.

Fix build issues with tox

---

streaming_data_types/_version.py
streaming_data_types/logdata_f142.py

Improve f142 serialisation performance

---

streaming_data_types/_version.py

PR #55 does not update the version number. This is disturbs the package submission to pypi. After this minor change is accepted, I will push the new package top pypi

Update _version.py after hs01 support has been added

---

streaming_data_types/eventdata_ev44.py
streaming_data_types/fbschemas/eventdata_ev44/Event44Message.py
tests/test_ev44.py

This patch is caused by patch in flatbuffer schema:
https://github.com/ess-dmsc/streaming-data-types/pull/82

Patching ev44 schema

---

streaming_data_types/_version.py

bumping version

---

streaming_data_types/_version.py

Bump the version
